### ISSUE TITLE
TODO list for automated prombench on GKE

### ISSUE THREAD

**Issue by sipian** [sipian/benchmark#5]
- [x] Support release number in `/benchmark release`
- [x] Build grafana graphs to compare metrics of 2 releases 
- [ ] Replace exposed service from LoadBalancer to Ingress
- [ ] Add alerting rules and post alerts as GitHub comments on being triggered
- [ ] Post a GitHub comment if the maintainer forgets to comment `/benchmark delete`
- [ ] Enable GitHub login in grafana & add grafana-kubernetes-app
